on:
  repository_dispatch: 
    types: [incident_report]

jobs:
   hundle_incident:
      runs-on: ubuntu-latest
      steps:
        - name: print incident details
          run: echo " incident reported "
    
